---
mode: apply
temp: /tmp
delete_pvc: True

# ISTIO
istio_version: 1.3.3

# CERT-MANAGER
certmanager_version: v0.11.0

# CLOUD DNS
clouddns_secret_name: sa-clouddns
clouddns_secret_filename: sa-clouddns.json

# KNATIVE
knative_version: v0.9.0
knative_certmanager: True

zookeeper_version: 5.1.0