---
- name: remove comments
  replace:
    path: "{{ role_path }}/latest_knative_github/{{ knative_version }}/{{ manifest }}.yaml"
    regexp: '^#.*$'
    replace: ''

- name: remove null section
  replace:
    path: "{{ role_path }}/latest_knative_github/{{ knative_version }}/{{ manifest }}.yaml"
    regexp: '^---\s*null\s*$'
    replace: ''

- name: add a sentinel value to allow us to remove the last yaml section
  lineinfile:
    path: "{{ role_path }}/latest_knative_github/{{ knative_version }}/{{ manifest }}.yaml"
    regexp: '^# EOF SENTINEL$'
    line: "# EOF SENTINEL"

- name: remove empty lines
  replace:
    path: "{{ role_path }}/latest_knative_github/{{ knative_version }}/{{ manifest }}.yaml"
    regexp: '^[\s\n]*$'
    replace: ''

- name: remove empty yaml sections
  replace:
    path: "{{ role_path }}/latest_knative_github/{{ knative_version }}/{{ manifest }}.yaml"
    regexp: '-{3}(?:-{3}|[\n\s]*)*-{3}'
    replace: '---'

- name: remove last empty yaml section (with the sentinel)
  replace:
    path: "{{ role_path }}/latest_knative_github/{{ knative_version }}/{{ manifest }}.yaml"
    regexp: '---[\n\s]*# EOF SENTINEL[\n\s]*$'
    replace: ''
