---
- hosts: all
  roles:
    - role: gke
      tags: [gke]
    - role: helm
      tags: [helm]
    - role: istio
      tags: [istio]
    - role: kafka
      tags: [kafka]
    - role: knative
      tags: [knative]
