---
- hosts: all
  roles:
    - role: gke
      tags: [gke]
    - role: helm
      tags: [helm]
    - role: istio
      tags: [istio]
    - role: cert-manager
      tags: [cert-manager]

    - role: certificates
      tags: [certificates]

    - role: kafka
      tags: [kafka]
    - role: knative
      tags: [knative]
    - role: filebeat
      tags: [filebeat]

    - role: knative-namespace
      tags: [knative-namespace]
